[*] Some small modifications

diff --git a/create_source_packages b/create_source_packages
--- a/create_source_packages
+++ b/create_source_packages
@@ -70,13 +70,13 @@ main()
 }
 
 
-if [[ $# -ne 1 || ! -d $1 ]]
+src_dir=$(cd $(dirname "$0") && pwd) || exit 1
+
+if [[ ! -d "$src_dir" ]]
 then
-	echo "Usage: $0 /path/to/package/sources" >&2
+	echo "Unable to get source directory." >&2
 	exit 1
 fi
-
-src_dir=$(cd "$1" && pwd) || exit 1
 
 main
 
